name: E2ETest
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - uses: NuGet/setup-nuget@v1.0.5
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-      
      - name: NuGet Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore Example4GithubActionAspNetMvcE2ETest.sln
      - run: msbuild Example4GithubActionAspNetMvcE2ETest.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: AppPublish
          path: .\bin\app.publish\
  
  e2e-linux:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - run: |
          sudo apt-get -qqy update 
          sudo apt-get -qqy --no-install-recommends install fonts-wqy-zenhei           
      - uses: actions/checkout@v2      
      - uses: actions/download-artifact@v2
        with:
          name: AppPublish
          path: ./bin/app.publish/        
      - run: |
          cd ./bin/app.publish
          xsp4 --port 8080 --nonstop &
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install      
      - run: yarn E2ETest -e host=http://localhost:8080      
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: E2ELinuxTestVideos
          path: ./cypress/videos/*
          
  e2e-windows:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - uses: actions/download-artifact@v2
        with:
          name: AppPublish
          path: .\bin\app.publish\
      - run: Start-Process -FilePath 'C:\Program Files (x86)\IIS Express\iisexpress.exe' -ArgumentList "/path:${PWD}\bin\app.publish\"      
      - run: yarn E2ETest
      - run: taskkill /IM iisexpress.exe
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: E2EWindowsTestVideos
          path: .\cypress\videos\*
